from sqlalchemy import Column, Integer, String, Boolean, Float, DateTime, ForeignKey
from sqlalchemy.sql import func

from database import Base


class SkinAnalysis(Base):
    __tablename__ = "skin_analyses"

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
        index=True
    )

    # Uploaded skin image location
    image_path = Column(
        String(500),
        nullable=False
    )

    # AI analysis results
    acne = Column(
        Boolean,
        nullable=False,
        default=False
    )

    pigmentation = Column(
        Boolean,
        nullable=False,
        default=False
    )

    dryness = Column(
        Boolean,
        nullable=False,
        default=False
    )

    sensitivity = Column(
        Boolean,
        nullable=False,
        default=False
    )

    redness = Column(
        Boolean,
        nullable=False,
        default=False
    )

    dark_circles = Column(
        Boolean,
        nullable=False,
        default=False
    )

    wrinkles = Column(
        Boolean,
        nullable=False,
        default=False
    )

    # AI confidence score
    confidence = Column(
        Float,
        nullable=True
    )

    # Short explanation/result generated by AI
    analysis_result = Column(
        String(1000),
        nullable=True
    )

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )